version: '3.7'
services:
  postgres:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      # copy the sql script to create tables
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
